//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LCD_Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_LCD_Test.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful connection. Try to restart color analyzer.
        /// </summary>
        public static string BadConnection {
            get {
                return ResourceManager.GetString("BadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. Black.
        /// </summary>
        public static string BlackPoint {
            get {
                return ResourceManager.GetString("BlackPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. Blue.
        /// </summary>
        public static string BluePoint {
            get {
                return ResourceManager.GetString("BluePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Bottom center.
        /// </summary>
        public static string BottomCenterPoint {
            get {
                return ResourceManager.GetString("BottomCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Bottom left.
        /// </summary>
        public static string BottomLeftPoint {
            get {
                return ResourceManager.GetString("BottomLeftPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Bottom right.
        /// </summary>
        public static string BottomRightPoint {
            get {
                return ResourceManager.GetString("BottomRightPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating zero....
        /// </summary>
        public static string CalibratingZeroCA {
            get {
                return ResourceManager.GetString("CalibratingZeroCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Center.
        /// </summary>
        public static string CenterPoint {
            get {
                return ResourceManager.GetString("CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the connection of the CA-310 color analyzer. Try reboot it and run zero calibration again.
        /// </summary>
        public static string CheckConnectionCA {
            get {
                return ResourceManager.GetString("CheckConnectionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check probe! Maybe need to change mode from 0-CAL to MEAS.
        /// </summary>
        public static string CheckProbe {
            get {
                return ResourceManager.GetString("CheckProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all fields?.
        /// </summary>
        public static string CleanFieldWarning {
            get {
                return ResourceManager.GetString("CleanFieldWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear fields.
        /// </summary>
        public static string ClearFieldsButton {
            get {
                return ResourceManager.GetString("ClearFieldsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectedCA {
            get {
                return ResourceManager.GetString("ConnectedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to CA-310....
        /// </summary>
        public static string ConnectingCA {
            get {
                return ResourceManager.GetString("ConnectingCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed or ended with an error.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to CA-310 released.
        /// </summary>
        public static string ConnectionReleasedCA {
            get {
                return ResourceManager.GetString("ConnectionReleasedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current measurement time is.
        /// </summary>
        public static string CurrentMeasurementTime {
            get {
                return ResourceManager.GetString("CurrentMeasurementTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current SN is.
        /// </summary>
        public static string CurrentSN {
            get {
                return ResourceManager.GetString("CurrentSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string DisconnectedCA {
            get {
                return ResourceManager.GetString("DisconnectedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting CA-310....
        /// </summary>
        public static string DisconnectingCA {
            get {
                return ResourceManager.GetString("DisconnectingCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during calibration.
        /// </summary>
        public static string ErrAtCalibration {
            get {
                return ResourceManager.GetString("ErrAtCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving to CSV.
        /// </summary>
        public static string ErrCSV {
            get {
                return ResourceManager.GetString("ErrCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in.
        /// </summary>
        public static string ErrIn {
            get {
                return ResourceManager.GetString("ErrIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to switch language.
        /// </summary>
        public static string ErrMsgLangSwitchFailed {
            get {
                return ResourceManager.GetString("ErrMsgLangSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error measuring at iteration .
        /// </summary>
        public static string ErrorAtMeasuringIteration {
            get {
                return ResourceManager.GetString("ErrorAtMeasuringIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error releasing connection.
        /// </summary>
        public static string ErrReleaseConnectionCA {
            get {
                return ResourceManager.GetString("ErrReleaseConnectionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to save results. Please, check file path and try again.
        /// </summary>
        public static string ErrSavingJSON {
            get {
                return ResourceManager.GetString("ErrSavingJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please a valid SN without special symbols.
        /// </summary>
        public static string ErrSerialNumberInput {
            get {
                return ResourceManager.GetString("ErrSerialNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please enter a number. Measurement time set to default.
        /// </summary>
        public static string ErrTimeInput {
            get {
                return ResourceManager.GetString("ErrTimeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string ErrUnexpected {
            get {
                return ResourceManager.GetString("ErrUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the SN first!.
        /// </summary>
        public static string FillSN {
            get {
                return ResourceManager.GetString("FillSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G. Green.
        /// </summary>
        public static string GreenPoint {
            get {
                return ResourceManager.GetString("GreenPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make zero calibration first!.
        /// </summary>
        public static string MakeZeroCalibration {
            get {
                return ResourceManager.GetString("MakeZeroCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured values.
        /// </summary>
        public static string MeasuredValuesPrefix {
            get {
                return ResourceManager.GetString("MeasuredValuesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement time (s):.
        /// </summary>
        public static string MeasurementTimeSec {
            get {
                return ResourceManager.GetString("MeasurementTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, connect CA-310 first.
        /// </summary>
        public static string MeasureWihoutConnectionError {
            get {
                return ResourceManager.GetString("MeasureWihoutConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring....
        /// </summary>
        public static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Middle left.
        /// </summary>
        public static string MiddleLeftPoint {
            get {
                return ResourceManager.GetString("MiddleLeftPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Middle right.
        /// </summary>
        public static string MiddleRightPoint {
            get {
                return ResourceManager.GetString("MiddleRightPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is switched to.
        /// </summary>
        public static string MsgLanguageSwitchedTo {
            get {
                return ResourceManager.GetString("MsgLanguageSwitchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. Red.
        /// </summary>
        public static string RedPoint {
            get {
                return ResourceManager.GetString("RedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for SN.
        /// </summary>
        public static string ResultsForSN {
            get {
                return ResourceManager.GetString("ResultsForSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved to JSON in.
        /// </summary>
        public static string SavedToJSON {
            get {
                return ResourceManager.GetString("SavedToJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save results.
        /// </summary>
        public static string SaveResultsButton {
            get {
                return ResourceManager.GetString("SaveResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all measurements have been taken, are you sure you want to save the result?.
        /// </summary>
        public static string SavingNotFullWarning {
            get {
                return ResourceManager.GetString("SavingNotFullWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number:.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Top center.
        /// </summary>
        public static string TopCenterPoint {
            get {
                return ResourceManager.GetString("TopCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Top left.
        /// </summary>
        public static string TopLeftPoint {
            get {
                return ResourceManager.GetString("TopLeftPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Top right.
        /// </summary>
        public static string TopRightPoint {
            get {
                return ResourceManager.GetString("TopRightPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero is calibrated.
        /// </summary>
        public static string ZeroCalibratedCA {
            get {
                return ResourceManager.GetString("ZeroCalibratedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Calibration.
        /// </summary>
        public static string ZeroCalibration {
            get {
                return ResourceManager.GetString("ZeroCalibration", resourceCulture);
            }
        }
    }
}
