//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCD_Test_Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCD_Test_Tool.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful connection. Try to restart color analyzer.
        /// </summary>
        internal static string BadConnection {
            get {
                return ResourceManager.GetString("BadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating zero....
        /// </summary>
        internal static string CalibratingZeroCA {
            get {
                return ResourceManager.GetString("CalibratingZeroCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the connection of the CA-310 color analyzer. Try reboot it and run zero calibration again.
        /// </summary>
        internal static string CheckConnectionCA {
            get {
                return ResourceManager.GetString("CheckConnectionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check probe! Maybe need to change mode from 0-CAL to MEAS.
        /// </summary>
        internal static string CheckProbe {
            get {
                return ResourceManager.GetString("CheckProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all fields?.
        /// </summary>
        internal static string CleanFieldWarning {
            get {
                return ResourceManager.GetString("CleanFieldWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ConnectedCA {
            get {
                return ResourceManager.GetString("ConnectedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to CA-310....
        /// </summary>
        internal static string ConnectingCA {
            get {
                return ResourceManager.GetString("ConnectingCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to CA-310 released.
        /// </summary>
        internal static string ConnectionReleasedCA {
            get {
                return ResourceManager.GetString("ConnectionReleasedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current measurement time is.
        /// </summary>
        internal static string CurrentMeasurementTime {
            get {
                return ResourceManager.GetString("CurrentMeasurementTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current SN is.
        /// </summary>
        internal static string CurrentSN {
            get {
                return ResourceManager.GetString("CurrentSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during calibration.
        /// </summary>
        internal static string ErrAtCalibration {
            get {
                return ResourceManager.GetString("ErrAtCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving to CSV.
        /// </summary>
        internal static string ErrCSV {
            get {
                return ResourceManager.GetString("ErrCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in.
        /// </summary>
        internal static string ErrIn {
            get {
                return ResourceManager.GetString("ErrIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to switch language.
        /// </summary>
        internal static string ErrMsgLangSwitchFailed {
            get {
                return ResourceManager.GetString("ErrMsgLangSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error measuring at iteration .
        /// </summary>
        internal static string ErrorAtMeasuringIteration {
            get {
                return ResourceManager.GetString("ErrorAtMeasuringIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error releasing connection.
        /// </summary>
        internal static string ErrReleaseConnectionCA {
            get {
                return ResourceManager.GetString("ErrReleaseConnectionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to save results. Please, check file path and try again.
        /// </summary>
        internal static string ErrSavingJSON {
            get {
                return ResourceManager.GetString("ErrSavingJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please a valid SN without special symbols.
        /// </summary>
        internal static string ErrSerialNumberInput {
            get {
                return ResourceManager.GetString("ErrSerialNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please enter a number. Measurement time set to default.
        /// </summary>
        internal static string ErrTimeInput {
            get {
                return ResourceManager.GetString("ErrTimeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        internal static string ErrUnexpected {
            get {
                return ResourceManager.GetString("ErrUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the SN first!.
        /// </summary>
        internal static string FillSN {
            get {
                return ResourceManager.GetString("FillSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make zero calibration first!.
        /// </summary>
        internal static string MakeZeroCalibration {
            get {
                return ResourceManager.GetString("MakeZeroCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured values.
        /// </summary>
        internal static string MeasuredValuesPrefix {
            get {
                return ResourceManager.GetString("MeasuredValuesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring....
        /// </summary>
        internal static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is switched to.
        /// </summary>
        internal static string MsgLanguageSwitchedTo {
            get {
                return ResourceManager.GetString("MsgLanguageSwitchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for SN.
        /// </summary>
        internal static string ResultsForSN {
            get {
                return ResourceManager.GetString("ResultsForSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved to JSON in.
        /// </summary>
        internal static string SavedToJSON {
            get {
                return ResourceManager.GetString("SavedToJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all measurements have been taken, are you sure you want to save the result?.
        /// </summary>
        internal static string SavingNotFullWarning {
            get {
                return ResourceManager.GetString("SavingNotFullWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero is calibrated.
        /// </summary>
        internal static string ZeroCalibratedCA {
            get {
                return ResourceManager.GetString("ZeroCalibratedCA", resourceCulture);
            }
        }
    }
}
