//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LCD_Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_LCD_Test.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already activated.
        /// </summary>
        public static string AlreadyActivated {
            get {
                return ResourceManager.GetString("AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive folder not found in {0}.
        /// </summary>
        public static string ArchiveFolderNotFound {
            get {
                return ResourceManager.GetString("ArchiveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt.
        /// </summary>
        public static string Attempt {
            get {
                return ResourceManager.GetString("Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful connection. Try to restart color analyzer.
        /// </summary>
        public static string BadConnection {
            get {
                return ResourceManager.GetString("BadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to batches.
        /// </summary>
        public static string Batches {
            get {
                return ResourceManager.GetString("Batches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. Black.
        /// </summary>
        public static string BlackPoint {
            get {
                return ResourceManager.GetString("BlackPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. Blue.
        /// </summary>
        public static string BluePoint {
            get {
                return ResourceManager.GetString("BluePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Bottom center.
        /// </summary>
        public static string BottomCenterPoint {
            get {
                return ResourceManager.GetString("BottomCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Bottom left.
        /// </summary>
        public static string BottomLeftPoint {
            get {
                return ResourceManager.GetString("BottomLeftPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Bottom right.
        /// </summary>
        public static string BottomRightPoint {
            get {
                return ResourceManager.GetString("BottomRightPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrated.
        /// </summary>
        public static string CalibratedCA {
            get {
                return ResourceManager.GetString("CalibratedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating zero....
        /// </summary>
        public static string CalibratingZeroCA {
            get {
                return ResourceManager.GetString("CalibratingZeroCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start upload: Device name is unknown.
        /// </summary>
        public static string CantStartUpload {
            get {
                return ResourceManager.GetString("CantStartUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Center.
        /// </summary>
        public static string CenterPoint {
            get {
                return ResourceManager.GetString("CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device channel has been successfully changed to {0}.
        /// </summary>
        public static string ChannelChanged {
            get {
                return ResourceManager.GetString("ChannelChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the connection of the CA-310 color analyzer. Try reboot it and run zero calibration again.
        /// </summary>
        public static string CheckConnectionCA {
            get {
                return ResourceManager.GetString("CheckConnectionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check probe! Maybe need to change mode from 0-CAL to MEAS.
        /// </summary>
        public static string CheckProbe {
            get {
                return ResourceManager.GetString("CheckProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose configuration….
        /// </summary>
        public static string ChooseConfiguration {
            get {
                return ResourceManager.GetString("ChooseConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all fields?.
        /// </summary>
        public static string CleanFieldWarning {
            get {
                return ResourceManager.GetString("CleanFieldWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results are saved. Clear all fields?.
        /// </summary>
        public static string CleanFieldWarningAfterSave {
            get {
                return ResourceManager.GetString("CleanFieldWarningAfterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear fields.
        /// </summary>
        public static string ClearFieldsButton {
            get {
                return ResourceManager.GetString("ClearFieldsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields and measurement results are cleared.
        /// </summary>
        public static string ClearFieldsDone {
            get {
                return ResourceManager.GetString("ClearFieldsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLI Upload Error for file: {0}. Exit code: {1}. Error: {2}.
        /// </summary>
        public static string CLI_ErrorFor {
            get {
                return ResourceManager.GetString("CLI_ErrorFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color analyzer error :(.
        /// </summary>
        public static string ColorAnalyzerErr {
            get {
                return ResourceManager.GetString("ColorAnalyzerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The service did not return a measurement result for {0}.
        /// </summary>
        public static string ColorServiceErr {
            get {
                return ResourceManager.GetString("ColorServiceErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations directory not found: {0}.
        /// </summary>
        public static string ConfigDirNotFound {
            get {
                return ResourceManager.GetString("ConfigDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectedCA {
            get {
                return ResourceManager.GetString("ConnectedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to CA-310....
        /// </summary>
        public static string ConnectingCA {
            get {
                return ResourceManager.GetString("ConnectingCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed or ended with an error.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to CA-310 released.
        /// </summary>
        public static string ConnectionReleasedCA {
            get {
                return ResourceManager.GetString("ConnectionReleasedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to containing.
        /// </summary>
        public static string Containing {
            get {
                return ResourceManager.GetString("Containing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of uploaded report archives in folder: {0}.
        /// </summary>
        public static string CopyOfUploadedArchivesInFolder {
            get {
                return ResourceManager.GetString("CopyOfUploadedArchivesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created batch for {0}.
        /// </summary>
        public static string CreatedBatchFor {
            get {
                return ResourceManager.GetString("CreatedBatchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV saving error: No data to save.
        /// </summary>
        public static string CsvDataErr {
            get {
                return ResourceManager.GetString("CsvDataErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV saving error: Location name not specified.
        /// </summary>
        public static string CsvLocationErr {
            get {
                return ResourceManager.GetString("CsvLocationErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV saving error: No serial number specified..
        /// </summary>
        public static string CsvSnErr {
            get {
                return ResourceManager.GetString("CsvSnErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizationService Error: Culture for language not found.
        /// </summary>
        public static string CultureNotFoundErr {
            get {
                return ResourceManager.GetString("CultureNotFoundErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current measurement time is.
        /// </summary>
        public static string CurrentMeasurementTime {
            get {
                return ResourceManager.GetString("CurrentMeasurementTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current SN: {0}.
        /// </summary>
        public static string CurrentSN {
            get {
                return ResourceManager.GetString("CurrentSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string DisconnectedCA {
            get {
                return ResourceManager.GetString("DisconnectedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting CA-310....
        /// </summary>
        public static string DisconnectingCA {
            get {
                return ResourceManager.GetString("DisconnectingCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during calibration.
        /// </summary>
        public static string ErrAtCalibration {
            get {
                return ResourceManager.GetString("ErrAtCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing CA channel: {0}.
        /// </summary>
        public static string ErrAtChangeChannel {
            get {
                return ResourceManager.GetString("ErrAtChangeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving to CSV.
        /// </summary>
        public static string ErrCSV {
            get {
                return ResourceManager.GetString("ErrCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in.
        /// </summary>
        public static string ErrIn {
            get {
                return ResourceManager.GetString("ErrIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement is out of expected range for this color.
        /// </summary>
        public static string ErrMeasurementOutOfRange {
            get {
                return ResourceManager.GetString("ErrMeasurementOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error in measurement validation.
        /// </summary>
        public static string ErrMeasurementValidation {
            get {
                return ResourceManager.GetString("ErrMeasurementValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to switch language.
        /// </summary>
        public static string ErrMsgLangSwitchFailed {
            get {
                return ResourceManager.GetString("ErrMsgLangSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error measuring at iteration .
        /// </summary>
        public static string ErrorAtMeasuringIteration {
            get {
                return ResourceManager.GetString("ErrorAtMeasuringIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in background task: {0}.
        /// </summary>
        public static string ErrorInBackgroundTask {
            get {
                return ResourceManager.GetString("ErrorInBackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error releasing connection.
        /// </summary>
        public static string ErrReleaseConnectionCA {
            get {
                return ResourceManager.GetString("ErrReleaseConnectionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to save results. Please, check file path and try again.
        /// </summary>
        public static string ErrSavingJSON {
            get {
                return ResourceManager.GetString("ErrSavingJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please a valid SN without special symbols.
        /// </summary>
        public static string ErrSerialNumberInput {
            get {
                return ResourceManager.GetString("ErrSerialNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please enter a number. Measurement time set to default.
        /// </summary>
        public static string ErrTimeInput {
            get {
                return ResourceManager.GetString("ErrTimeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        public static string ErrUnexpected {
            get {
                return ResourceManager.GetString("ErrUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrWithArg {
            get {
                return ResourceManager.GetString("ErrWithArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed measurement for location.
        /// </summary>
        public static string FailedMeasurementForLocation {
            get {
                return ResourceManager.GetString("FailedMeasurementForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute CLI for {0}. Error: {1}.
        /// </summary>
        public static string FailedToExecuteCLI {
            get {
                return ResourceManager.GetString("FailedToExecuteCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the SN first!.
        /// </summary>
        public static string FillSN {
            get {
                return ResourceManager.GetString("FillSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G. Green.
        /// </summary>
        public static string GreenPoint {
            get {
                return ResourceManager.GetString("GreenPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct serial number from Latin letters and digits.
        /// </summary>
        public static string IncorrectFormatForSNErr {
            get {
                return ResourceManager.GetString("IncorrectFormatForSNErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the correct measurement time (greater than 0).
        /// </summary>
        public static string IncorrectMeasTimeFormat {
            get {
                return ResourceManager.GetString("IncorrectMeasTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid report configuration.
        /// </summary>
        public static string InvalidReportConfiguration {
            get {
                return ResourceManager.GetString("InvalidReportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid result.
        /// </summary>
        public static string InvalidResultErr {
            get {
                return ResourceManager.GetString("InvalidResultErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalisationService Error: Formatting string for key.
        /// </summary>
        public static string LocalizationServiceFormatErr {
            get {
                return ResourceManager.GetString("LocalizationServiceFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalisationService Error: ResourceManager for key.
        /// </summary>
        public static string LocalizationServiceKeyErr {
            get {
                return ResourceManager.GetString("LocalizationServiceKeyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalisationService Warning: Resource with key not found in .resx for culture.
        /// </summary>
        public static string LocalizationServiceResErr {
            get {
                return ResourceManager.GetString("LocalizationServiceResErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness for black color unexpectedly high, please check color analyzer position.
        /// </summary>
        public static string LvIsTooHigh {
            get {
                return ResourceManager.GetString("LvIsTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution: The measured brightness Lv is too low.
        /// </summary>
        public static string LvIsTooLow {
            get {
                return ResourceManager.GetString("LvIsTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make zero calibration first!.
        /// </summary>
        public static string MakeZeroCalibration {
            get {
                return ResourceManager.GetString("MakeZeroCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to find a status for a measurement point to update.
        /// </summary>
        public static string MeasButStatusErr {
            get {
                return ResourceManager.GetString("MeasButStatusErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured values.
        /// </summary>
        public static string MeasuredValuesPrefix {
            get {
                return ResourceManager.GetString("MeasuredValuesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result for {0}: {1}.
        /// </summary>
        public static string MeasurementResult {
            get {
                return ResourceManager.GetString("MeasurementResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement time (s):.
        /// </summary>
        public static string MeasurementTimeSec {
            get {
                return ResourceManager.GetString("MeasurementTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement validation successfully passed.
        /// </summary>
        public static string MeasurementValidationPassed {
            get {
                return ResourceManager.GetString("MeasurementValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, connect CA-310 first.
        /// </summary>
        public static string MeasureWihoutConnectionError {
            get {
                return ResourceManager.GetString("MeasureWihoutConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring....
        /// </summary>
        public static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Middle left.
        /// </summary>
        public static string MiddleLeftPoint {
            get {
                return ResourceManager.GetString("MiddleLeftPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Middle right.
        /// </summary>
        public static string MiddleRightPoint {
            get {
                return ResourceManager.GetString("MiddleRightPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is switched to.
        /// </summary>
        public static string MsgLanguageSwitchedTo {
            get {
                return ResourceManager.GetString("MsgLanguageSwitchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for report generation.
        /// </summary>
        public static string NoDataFoundForReportGenerator {
            get {
                return ResourceManager.GetString("NoDataFoundForReportGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports found for upload..
        /// </summary>
        public static string NoReportsFoundForUpload {
            get {
                return ResourceManager.GetString("NoReportsFoundForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SN.
        /// </summary>
        public static string NoSNErr {
            get {
                return ResourceManager.GetString("NoSNErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not calibrated.
        /// </summary>
        public static string NotCalibratedCa {
            get {
                return ResourceManager.GetString("NotCalibratedCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, try to measure again.
        /// </summary>
        public static string PleaseTryToMeasureAgain {
            get {
                return ResourceManager.GetString("PleaseTryToMeasureAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to upload: {0}.
        /// </summary>
        public static string ReadyToUpload {
            get {
                return ResourceManager.GetString("ReadyToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. Red.
        /// </summary>
        public static string RedPoint {
            get {
                return ResourceManager.GetString("RedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated successfully.
        /// </summary>
        public static string ReportGeneratedSuccessfully {
            get {
                return ResourceManager.GetString("ReportGeneratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generation failed.
        /// </summary>
        public static string ReportGenerationFailed {
            get {
                return ResourceManager.GetString("ReportGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for SN.
        /// </summary>
        public static string ResultsForSN {
            get {
                return ResourceManager.GetString("ResultsForSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results successfully saved.
        /// </summary>
        public static string ResultsSaved {
            get {
                return ResourceManager.GetString("ResultsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect path for calling an external program.
        /// </summary>
        public static string RunExternalAppInvalidPathErr {
            get {
                return ResourceManager.GetString("RunExternalAppInvalidPathErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: External program file not found in {0}.
        /// </summary>
        public static string RunExternalAppNotFoundErr {
            get {
                return ResourceManager.GetString("RunExternalAppNotFoundErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when launching an external program: {0}.
        /// </summary>
        public static string RunExternalAppUnexpectedErr {
            get {
                return ResourceManager.GetString("RunExternalAppUnexpectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save has been canceled by the user.
        /// </summary>
        public static string SaveCanceled {
            get {
                return ResourceManager.GetString("SaveCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved to JSON in.
        /// </summary>
        public static string SavedToJSON {
            get {
                return ResourceManager.GetString("SavedToJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error: No device data.
        /// </summary>
        public static string SaveJSONErrDeviceIsEmpty {
            get {
                return ResourceManager.GetString("SaveJSONErrDeviceIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when saving to JSON for SN.
        /// </summary>
        public static string SaveJSONErrForSN {
            get {
                return ResourceManager.GetString("SaveJSONErrForSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result for this measurement point still appears to be incorrect. Do you want to save it anyway?.
        /// </summary>
        public static string SaveNotCorrectResultQuestion {
            get {
                return ResourceManager.GetString("SaveNotCorrectResultQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save results.
        /// </summary>
        public static string SaveResultsButton {
            get {
                return ResourceManager.GetString("SaveResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all measurements have been taken, are you sure you want to save the result?.
        /// </summary>
        public static string SavingNotFullWarning {
            get {
                return ResourceManager.GetString("SavingNotFullWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number:.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement validation is skipped.
        /// </summary>
        public static string SkippedMeasurementValidaton {
            get {
                return ResourceManager.GetString("SkippedMeasurementValidaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial number cannot be empty.
        /// </summary>
        public static string SnCantBeEmpty {
            get {
                return ResourceManager.GetString("SnCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting parallel upload of {0} files.
        /// </summary>
        public static string StartingParallelUploadOf {
            get {
                return ResourceManager.GetString("StartingParallelUploadOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting report generation....
        /// </summary>
        public static string StartingReportGeneration {
            get {
                return ResourceManager.GetString("StartingReportGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting reports upload....
        /// </summary>
        public static string StartingReportUploading {
            get {
                return ResourceManager.GetString("StartingReportUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting upload of {0}.
        /// </summary>
        public static string StartingUploadOf {
            get {
                return ResourceManager.GetString("StartingUploadOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test with a number: {0}.
        /// </summary>
        public static string TestFormatString {
            get {
                return ResourceManager.GetString("TestFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing of the device with SN has begun: {0}.
        /// </summary>
        public static string TestStartInfo {
            get {
                return ResourceManager.GetString("TestStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Top center.
        /// </summary>
        public static string TopCenterPoint {
            get {
                return ResourceManager.GetString("TopCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Top left.
        /// </summary>
        public static string TopLeftPoint {
            get {
                return ResourceManager.GetString("TopLeftPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Top right.
        /// </summary>
        public static string TopRightPoint {
            get {
                return ResourceManager.GetString("TopRightPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected measurement error.
        /// </summary>
        public static string UnexpectedMeasurementErr {
            get {
                return ResourceManager.GetString("UnexpectedMeasurementErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded successfully. Total files uploaded: {0}.
        /// </summary>
        public static string UploadedSuccessfully {
            get {
                return ResourceManager.GetString("UploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload process failed.
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload process finished with failures. Total files failed: {0}.
        /// </summary>
        public static string UploadFinishedWithFail {
            get {
                return ResourceManager.GetString("UploadFinishedWithFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful for {0}.
        /// </summary>
        public static string UploadSuccessfulFor {
            get {
                return ResourceManager.GetString("UploadSuccessfulFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation message.
        /// </summary>
        public static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel resource cleanup is complete.
        /// </summary>
        public static string ViewModelCleared {
            get {
                return ResourceManager.GetString("ViewModelCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel resources are being cleared....
        /// </summary>
        public static string ViewModelClearing {
            get {
                return ResourceManager.GetString("ViewModelClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Failed to cleanup {0}. Error: {1}.
        /// </summary>
        public static string WarningFailedToCleanup {
            get {
                return ResourceManager.GetString("WarningFailedToCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the “Zero Calibration” button to connect the color analyzer and fill in the SN to start the measurements.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A working folder has been created to store the results.
        /// </summary>
        public static string WorkFolderCreated {
            get {
                return ResourceManager.GetString("WorkFolderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder has been created for the device with SN.
        /// </summary>
        public static string WorkFolderCreatedForSN {
            get {
                return ResourceManager.GetString("WorkFolderCreatedForSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during initialisation of working folders.
        /// </summary>
        public static string WorkingFolderInitErr {
            get {
                return ResourceManager.GetString("WorkingFolderInitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero is calibrated.
        /// </summary>
        public static string ZeroCalibratedCA {
            get {
                return ResourceManager.GetString("ZeroCalibratedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Calibration.
        /// </summary>
        public static string ZeroCalibration {
            get {
                return ResourceManager.GetString("ZeroCalibration", resourceCulture);
            }
        }
    }
}
