main_tests:
  Brightness:
    min: 395
    typ: 405
    max: 420
  Brightness_uniformaty:
    min: 80.75
    typ: 85.0
    max: 89.25
  Contrast:
    min: 1140.0
    typ: 1200.0
    max: 1260.0
  Cg_rgb_area:
    min: 90.25
    typ: 95.0
    max: 99.75
  Cg_ntsc_area:
    min: 68.4
    typ: 72.0
    max: 75.6
  Cg_rgb:
    min: 90.25
    typ: 95.0
    max: 99.75
  Cg_ntsc:
    min: 100.25
    typ: 110.0
    max: 99.75
  Temperature:
    min: 6175.0
    typ: 6500.0
    max: 6825.0
  Delta_e:
    min: 1
    typ: 3
    max: 4
  Red_x:
    min: 0.608
    typ: 0.64
    max: 0.672
  Red_y:
    min: 0.3135
    typ: 0.33
    max: 0.3465
  Green_x:
    min: 0.285
    typ: 0.3
    max: 0.315
  Green_y:
    min: 0.57
    typ: 0.6
    max: 0.63
  Blue_x:
    min: 0.1425
    typ: 0.15
    max: 0.1575
  Blue_y:
    min: 0.057
    typ: 0.06
    max: 0.063
  White_x:
    min: 0.2971
    typ: 0.3127
    max: 0.3283
  White_y:
    min: 0.3126
    typ: 0.329
    max: 0.3455


